/*******************************************************************************
This file is part of the VIENNAAddIn project

Licensed under GNU General Public License V3 http://gplv3.fsf.org/

For further information on the VIENNAAddIn project please visit 
http://vienna-add-in.googlecode.com
*******************************************************************************/
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.Xml;
using System.Xml.Schema;
using System.IO;
using EA;
using VIENNAAddIn.Utils;
using VIENNAAddIn.Exceptions;
using VIENNAAddIn.constants;
using VIENNAAddIn.common;

namespace VIENNAAddIn.CCTS {
    public partial class QDTGenerator : Form, GeneratorCallBackInterface
    {


        #region Variables
        private Repository repository;
        private String scope;
        private bool annotate = true;
        private bool blnAlias;
        private bool blnIncludeLinkedSchema;
        
        private bool withGUI;
        private GeneratorCallBackInterface caller;

        private bool DEBUG;

        //The path where the generated schema(s) will be saved
        private String path = "";       
        private String targetNameSpacePrefix = "qdt";

        //These variables are used to make a distinction between namespaces of the same type        
        static int countUDTImports = 0;
        static int countENUMImports = 0;
        static int countBIEImports = 0;

        //This ArrayList holds a List of all auxilliary schmeas
        //that had to be created for this schema to be valid
        private System.Collections.ArrayList alreadyCreatedSchemas = new ArrayList();

        //This arraylist hold a list of auxilliary schema that generated by BusinessLibraryGenerator
        private ArrayList alreadyCreatedSchemasBLGen;
        
        //if generate from anyLevel, its value will be true, otherwise if generated from specific package it will be false;
        private bool isAnyLevelGeneration = false;

        #endregion Variables

        #region Constructor
        /// <sUMM2ary>
        /// This constructor constructs a regular QDTGenerator with a GUI
        /// </sUMM2ary>
        /// <param name="repository"></param>
        /// <param name="scope"></param>
        public QDTGenerator(EA.Repository repository, String scope, bool annotate) {
            
            //Set the debug mode
            DEBUG = Utility.DEBUG;

            this.repository = repository;
            this.scope = scope;
            this.annotate = annotate;
            this.withGUI = true;
            isAnyLevelGeneration = false;

            InitializeComponent();

            this.setActivePackageLabel();
        }

        /// <summary>
        /// This constructor special for any-level schema generator
        /// </summary>
        /// <param name="repository"></param>
        /// <param name="scope"></param>
        /// <param name="annotate"></param>
        /// <param name="path"></param>
        /// <param name="alreadyCreatedSchemasBLGen"></param>
        public QDTGenerator(EA.Repository repository, String scope, bool annotate, bool blnAlias, 
            bool blnIncludeLinkedSchema, string path, ArrayList alreadyCreatedSchemasBLGen)
        {

            //Set the debug mode
            DEBUG = Utility.DEBUG;

            this.repository = repository;
            this.scope = scope;
            this.annotate = annotate;
            this.withGUI = false;
            this.blnAlias = blnAlias;
            this.blnIncludeLinkedSchema = blnIncludeLinkedSchema;
            
            this.path = path;
            this.isAnyLevelGeneration = true;
            this.alreadyCreatedSchemasBLGen = alreadyCreatedSchemasBLGen;

            InitializeComponent();

            this.setActivePackageLabel();
        }

        /// <sUMM2ary>
        /// This constructor constructs a QDTGenerator without a GUI
        /// </sUMM2ary>
        /// <param name="repository"></param>
        /// <param name="scope"></param>
        public QDTGenerator(EA.Repository repository, String scope, bool annotate, bool blnIncludeLinkedSchema, 
            bool blnAlias, String path, GeneratorCallBackInterface caller) 
        {
            //Set the debug mode
            DEBUG = Utility.DEBUG;

            this.caller = caller;
            this.repository = repository;
            this.scope = scope;
            this.annotate = annotate;
            this.blnIncludeLinkedSchema = blnIncludeLinkedSchema;
            this.blnAlias = blnAlias;
            this.withGUI = false;
            //Set the path from the caller because the CDT Generator now operates in not visible
            //mode and hence no path is determined in this class
            this.path = path;
            isAnyLevelGeneration = false;

        }
        #endregion

        #region public methods
        /// <sUMM2ary>
        /// Setze den Generator zurück
        /// </sUMM2ary>
        /// <param name="scope"></param>
        public void resetGenerator(String scope) {
            this.scope = scope;
            this.alreadyCreatedSchemas = new ArrayList();
            if (this.withGUI) {
                this.progressBar1.Value = this.progressBar1.Minimum;
                this.setActivePackageLabel();
                this.statusTextBox.Text = "";
            }
        }
        
        public String TargetNameSpacePrefix {
            get { return targetNameSpacePrefix; }
            set { targetNameSpacePrefix = value; }
        }

        /// <sUMM2ary>
        /// Generates a schema from the QDTs
        /// </sUMM2ary>
        /// <param name="p"></param>
        /// <returns></returns>
        public System.Collections.ICollection generateSchema(EA.Package p) {
            
            XmlSchema schema = new XmlSchema();
            schema.ElementFormDefault = XmlSchemaForm.Qualified;
            schema.AttributeFormDefault = XmlSchemaForm.Unqualified;
            schema.Version = XMLTools.getSchemaVersionFromPackage(p);

            //Add the necessary namespaces for the QDT schema
            addNameSpaces(schema);

            //Add the imports
            addImports(schema);


            int elementCount = 0;
            //Iterate through the CDTs
            foreach (EA.Element e in p.Elements) {
                elementCount++;
                if (e.Stereotype.Equals(CCTS_Types.QDT.ToString())) {
                    schema.Items.Add(getSchemaElement(e, schema));
                }
                //After every 20th iteration we perform a progress step
                if (elementCount % 20 == 0)
                    this.performProgressStep();
            }

            //Validate the Schema
            XmlSchemaSet xsdSet = new XmlSchemaSet();
            xsdSet.XmlResolver = null;
            xsdSet.ValidationEventHandler += new ValidationEventHandler(ValidationCallbackOne);
            try {
                xsdSet.Add(schema);
                //xsdSet.Compile();
            }
            catch (XmlSchemaException xse) {
                //Console.Write(xse.Message.ToString());
                //Console.Write(xse.StackTrace.ToString());
                throw xse;
            }
                       
            return xsdSet.Schemas();
        }

        /// <sUMM2ary>
        /// Is called from extern to append a message to this GUI
        /// </sUMM2ary>
        /// <param name="type"></param>
        /// <param name="message"></param>
        public void appendMessage(String type, String message, String packageName) {
            if (type == "info")
                this.appendInfoMessage(message, packageName);
            else if (type == "warn")
                this.appendWarnMessage(message, packageName);
            else if (type == "error")
                this.appendErrorMessage(message, packageName);

        }


        #endregion

        #region private methods

        /// <sUMM2ary>
        /// Returns a Schema Element
        /// This method can either return a complexType or a SimpleType,
        /// depending on the basis of the QDT
        /// </sUMM2ary>
        /// <param name="e"></param>
        /// <param name="schema"></param>
        /// <returns></returns>
        private XmlSchemaType getSchemaElement(EA.Element e, XmlSchema schema) {

            object[] obj = getBaseTypeName(e, schema);
            
            XmlQualifiedName xmlQualName = (XmlQualifiedName)obj[0];

            //Build in data type
            if (((Boolean)obj[1]) == true) {
                XmlSchemaComplexType complexType = new XmlSchemaComplexType();
                complexType.Name = XMLTools.getXMLName(e.Name) + "Type";

                //Annotate it?
                if (annotate)
                    complexType.Annotation = this.getQDTAnnotation(e);

                XmlSchemaSimpleContent simpleContent = new XmlSchemaSimpleContent();
                XmlSchemaSimpleContentRestriction simpleContent_restriction = new XmlSchemaSimpleContentRestriction();
                XmlSchemaSimpleContentExtension simpleContent_Ext = new XmlSchemaSimpleContentExtension();
                
                //blum slesai-Kristina
                simpleContent_Ext.BaseTypeName = new XmlQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
                simpleContent_restriction.BaseTypeName = xmlQualName;

                //Is there an OCL constraint we have to incorporate?
                String CONType = ((EA.Attribute)obj[3]).Type;
                //So far, processOCL method return null- so comment it, Kristina Aug'08
                //OCLMapper.processOCL(simpleContent_restriction, e, this.repository.GetPackageByID(e.PackageID), this, CONType);

                //In order to restrict the usage of attributes to the ones specified
                //in the QDT we have to add the prohibited attributes here
                IList attributes = (ArrayList)obj[2];
                if (attributes != null && attributes.Count != 0) {
                    foreach (String s in attributes) {
                        XmlSchemaAttribute at = new XmlSchemaAttribute();                                                
                        at.Use = XmlSchemaUse.Prohibited;
                        at.Name = s;
                        simpleContent_restriction.Attributes.Add(at);
                        //simpleContent_Ext.Attributes.Add(at);
                    }
                }

                //Those attributes whose multiplicity is 1..1 must be added here as well (with use=required)
                foreach (EA.Attribute attr in e.Attributes) {
                    if (attr.Stereotype.ToString().Equals(CCTS_Types.SUP.ToString()) && 
                        isRequired(attr)) {
                        XmlSchemaAttribute a = new XmlSchemaAttribute();                        
                        a.Name = attr.Name;
                        a.SchemaTypeName = new XmlQualifiedName(getXSDType(attr, e), "http://www.w3.org/2001/XMLSchema");
                        a.Use = XmlSchemaUse.Required;
                        simpleContent_restriction.Attributes.Add(a);
                        //simpleContent_Ext.Attributes.Add(a);
                    }
                }


                simpleContent.Content = simpleContent_restriction;
                complexType.ContentModel = simpleContent;

                return complexType;
            }
            ////No build in datatype
            else {
                XmlSchemaComplexType complexType = new XmlSchemaComplexType();
                complexType.Name = XMLTools.getXMLName(e.Name) + "Type";

                ////Annotate it?
                if (annotate)
                    complexType.Annotation = this.getQDTAnnotation(e);

                XmlSchemaSimpleContent simpleContent = new XmlSchemaSimpleContent();
                XmlSchemaSimpleContentExtension simpleContent_extension = new XmlSchemaSimpleContentExtension();                                
                simpleContent_extension.BaseTypeName = xmlQualName;

                //Iterate through the properties of the QDT
                foreach (EA.Attribute attribute in e.Attributes) {
                    if (attribute.Stereotype.ToString().Equals(CCTS_Types.SUP.ToString())) {
                        XmlSchemaAttribute att = new XmlSchemaAttribute();
                        //Annotate the attribute
                        if (annotate)
                            att.Annotation = this.getAttributeAnnotation(attribute);
                        att.Name = attribute.Name;
                        att.SchemaTypeName = new XmlQualifiedName(getXSDType(attribute, e), "http://www.w3.org/2001/XMLSchema");                        
                        //If the mulitplicity of the attribute is 1..1 then the use
                        //attribute must be set to required
                        if (isRequired(attribute))
                            att.Use = XmlSchemaUse.Required;
                        simpleContent_extension.Attributes.Add(att);
                    }
                }

                simpleContent.Content = simpleContent_extension;
                complexType.ContentModel = simpleContent;

                return complexType;
            }
        }


        /// <sUMM2ary>
        /// Determines whether the use of the Attribute is required or not
        /// The use of the attribute is required if the multiplicity is set to 1..1
        /// </sUMM2ary>
        /// <param name="a"></param>
        /// <returns></returns>
        private bool isRequired(EA.Attribute a) {
            bool b = false;
            if ((a.LowerBound != null && a.LowerBound.Equals("1")) &&
                (a.UpperBound != null && a.UpperBound.Equals("1")))
                b = true;
            return b;
        }





        /// <sUMM2ary>
        /// Returns the base type of this qdt element
        /// The base type is the type of the CON attribute
        /// </sUMM2ary>
        /// <param name="e"></param>
        /// <returns>object array
        /// [0] = QualifiedName (XmlQualifiedName)
        /// [1] = buildInType (true/false)
        /// [2] = AttributeList (List)
        /// [3] = the CON Attribute
        ///</returns>
        private object [] getBaseTypeName(EA.Element e, XmlSchema schema) {

            XmlQualifiedName xmlQualifiedName = null;
            System.Collections.IList attributesOfCDT = null;
            bool isBuildIn = true;
            EA.Attribute conAttribute = null;

            try {

                //Get the CON Attribute
                foreach (EA.Attribute attribute in e.Attributes) {
                    if (attribute.Stereotype.ToString().Equals(CCTS_Types.CON.ToString())) {
                        conAttribute = attribute;
                        break;
                    }
                }

                //No CON Attribute - throw an exception
                if (conAttribute == null)
                    throw new XMLException("The element " + e + " has no CON attribute. Unable to proceed with schema generation");

                //If the CON Attribute has no classifierID, a build in type has been taken
                EA.Element el = null;
                try {
                    el = this.repository.GetElementByID(conAttribute.ClassifierID);
                    isBuildIn = false;
                }
                catch (Exception eex) {
                    this.appendErrorMessage("Can not find classifier ID for element " + e.Name, "Error occurs when trying to get classifier ID fo element "
                        + e.Name + " in package " + this.repository.GetPackageByID(e.PackageID).Name);
                    return null;
                }

                EA.Element classifierElement = null;

                if (!isBuildIn) {
                    //Get the classifier element
                    //In the case of a non build in type this is the ENUM
                    classifierElement = this.repository.GetElementByID(conAttribute.ClassifierID);
                }
                else {
                    //Get the classifier element
                    //In the case of a build in type this is the underlying CDT
                    classifierElement = getCDTofQDT(e);
                    if (classifierElement == null)
                        this.appendErrorMessage("Could not find the underlying CDT for the QDT " + e.Name, this.scope.ToString());

                    //We have to get the attributes of the CDT
                    attributesOfCDT = getProhibitedAttributesOfCDT(e);
                }


                //Is there already an XML schema for this library?
                EA.Package importPackage = this.repository.GetPackageByID(classifierElement.PackageID);
                String stereotype = importPackage.Element.Stereotype.ToString();
                String s = "";

                //if the generation is from any level generation
                if (isAnyLevelGeneration)
                {
                    String sBLGen = "";
                    //is the schema already included in global array?
                    if ((s = isSchemaAlreadyIncluded(importPackage.Name)) == "" && (sBLGen = isAlreadyInBLGenArray(importPackage.Name)) != "")
                    {
                        #region for any level package generation, to check if there was previously generated schema
                        ////We need to add an import statement for the newly generated schema
                        ////to the original schema

                        AuxilliarySchema aux = new AuxilliarySchema();
                        aux.Namespace = XMLTools.getNameSpace(this.repository, importPackage);
                        aux.NamespacePrefix = XMLTools.getNameSpacePrefix(importPackage, DeterminePrefix(importPackage));//"qdt" + ++countUDTImports);
                        aux.PackageOfOrigin = importPackage.Name.ToString();

                        String schemaName = "";
                        schemaName = XMLTools.getSchemaName(this.repository.GetPackageByID(importPackage.PackageID));


                        String importPath = XMLTools.getImportPathForSchema(this.repository.GetPackageByID(importPackage.PackageID), repository, schemaName, scope, this.blnAlias);

                        addImport(schema, importPath, aux.Namespace);

                        //We need to add the namespace of this schema to the main schema
                        schema.Namespaces.Add(aux.NamespacePrefix, aux.Namespace);

                        //Set the namespace to the variable which is then used down below
                        s = aux.Namespace;

                        //add the schema to local alreadyCreatedSchema
                        this.alreadyCreatedSchemas.Add(aux);
                        #endregion
                    }
                }

                //Is this schema already included in local array?
                if ((s = isSchemaAlreadyIncluded(importPackage.Name)) == "")
                {
                    if (!this.blnIncludeLinkedSchema)
                    {
                        #region Include linked schema unchecked - for local generation only
                        AuxilliarySchema aux = new AuxilliarySchema();
                        aux.Namespace = XMLTools.getNameSpace(this.repository, importPackage);
                        aux.NamespacePrefix = XMLTools.getNameSpacePrefix(importPackage, DeterminePrefix(importPackage));
                        aux.PackageOfOrigin = importPackage.Name.ToString();
                        this.alreadyCreatedSchemas.Add(aux);

                        String schemaName = "";
                        schemaName = XMLTools.getSchemaName(this.repository.GetPackageByID(importPackage.PackageID));

                        String importPath = XMLTools.getImportPathForSchema(this.repository.GetPackageByID(importPackage.PackageID), repository, schemaName, scope, this.blnAlias);

                        addImport(schema, importPath, aux.Namespace);

                        //We need to add the namespace of this schema to the main schema
                        schema.Namespaces.Add(aux.NamespacePrefix, aux.Namespace);

                        //Set the namespace to the variable which is then used down below
                        s = aux.Namespace;
                        #endregion
                    }
                    else
                    {
                        #region Included linked schema Checked
                        //Create an Auxilliary schema and store it in the collection - later we have to
                        //add it to the main schema collection
                        AuxilliarySchema aux = new AuxilliarySchema();
                        System.Collections.ICollection result = null;

                        if (stereotype.Equals(CCTS_Types.CDTLibrary.ToString()))
                        {
                            result = new CDTGenerator(this.repository, importPackage.PackageID.ToString(), annotate, this.path, getCaller()).generateSchema(importPackage);
                            aux.NamespacePrefix = XMLTools.getNameSpacePrefix(importPackage, "udt" + ++countUDTImports);
                        }
                        else if (stereotype.Equals(CCTS_Types.ENUMLibrary.ToString()))
                        {
                            result = new ENUMGenerator(this.repository, importPackage.PackageID.ToString(), annotate, this.path, getCaller()).generateSchema(importPackage);
                            aux.NamespacePrefix = XMLTools.getNameSpacePrefix(importPackage, "enum" + ++countENUMImports);
                        }
                        else
                        {
                            //If the stereotype is neither CDT nor QDT we have to raise an error here
                            this.appendErrorMessage("The CON Attribute of the element " + e.Name + " points to an element in the following library (" + stereotype + "): " + importPackage.Name, importPackage.Name);
                            throw new XMLException("");
                        }

                        aux.Namespace = XMLTools.getNameSpace(this.repository, importPackage);
                        aux.PackageOfOrigin = importPackage.Name.ToString();
                        aux.Schemas = result;
                        
                        this.alreadyCreatedSchemas.Add(aux);

                        if (isAnyLevelGeneration)
                            this.alreadyCreatedSchemasBLGen.Add(aux);

                        
                        String schemaPath = "";
                        String schemaName = "";
                        schemaName = XMLTools.getSchemaName(this.repository.GetPackageByID(importPackage.PackageID));
                        schemaPath = XMLTools.getSavePathForSchema(this.repository.GetPackageByID(importPackage.PackageID), repository, this.blnAlias);
                        String filename = path + schemaPath + schemaName;

                        //Write the schema(s)
                        foreach (XmlSchema schema1 in result)
                        {
                            //Create the path
                            System.IO.Directory.CreateDirectory(path + schemaPath);
                            Stream outputStream = System.IO.File.Open(filename, FileMode.Create);
                            schema1.Write(outputStream);
                            outputStream.Close();
                        }

                        //We need to add an import statement for the newly generated schema
                        //to the original schema
                        String importPath = XMLTools.getImportPathForSchema(this.repository.GetPackageByID(importPackage.PackageID), repository, schemaName, scope, this.blnAlias);

                        addImport(schema, importPath, aux.Namespace);

                        //We need to add the namespace of this schema to the main schema
                        schema.Namespaces.Add(aux.NamespacePrefix, aux.Namespace);

                        //Set the namespace to the variable which is then used down below
                        s = aux.Namespace;

                        #endregion
                    }
                }

                xmlQualifiedName = new XmlQualifiedName(classifierElement.Name + "Type", s);

            }
            catch (XMLException xmlException) {               
                throw xmlException;
            }
            catch (Exception ex) {
                this.appendWarnMessage(ex.Message, this.getPackageName());                
                xmlQualifiedName = new XmlQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
            }

            object[] rv = { xmlQualifiedName, isBuildIn, attributesOfCDT, conAttribute };
            return rv;
        }

        private string DeterminePrefix(Package importPackage)
        {
            if (importPackage.Element.Stereotype.Equals(CCTS_Types.CDTLibrary.ToString()))
                return "udt" + ++countUDTImports;
            else
            if (importPackage.Element.Stereotype.Equals(CCTS_Types.ENUMLibrary.ToString()))
                return "enum" + ++countENUMImports;

            return "";
        }


        /// <sUMM2ary>
        /// Get the attributes of the CDT
        /// </sUMM2ary>
        /// <param name="e"></param>
        /// <returns></returns>
        private IList getProhibitedAttributesOfCDT(EA.Element e) {
            IList list = null;
            //Get the CDT on which the QDT is based on via the basedOn dependency
            foreach (EA.Connector con in e.Connectors) {
                if (con.Stereotype.ToString() == CCTS_Types.basedOn.ToString()) {
                    //Get the supplier of the connector
                    EA.Element cdt = this.repository.GetElementByID(con.SupplierID);
                    list = new ArrayList();
                    //Copy the SUP attributes of the QDT in a List
                    IList qdtAttributes = new ArrayList();
                    foreach (EA.Attribute a in e.Attributes) {
                        if (a.Stereotype.ToString() == CCTS_Types.SUP.ToString())
                            qdtAttributes.Add(a.Name);
                    }
                    
                    //copy the attributes of the cdt which are not contained
                    //in the qdt
                    foreach (EA.Attribute attribute in cdt.Attributes) {
                        if (attribute.Stereotype.ToString() == CCTS_Types.SUP.ToString()) {
                            if (!qdtAttributes.Contains(attribute.Name))
                                list.Add(attribute.Name);
                        }
                    }
                }
            }
            return list;
        }

        /// <sUMM2ary>
        /// Get the CDT which is the basis for the passed QDT
        /// </sUMM2ary>
        /// <param name="e"></param>
        /// <returns></returns>
        private EA.Element getCDTofQDT(EA.Element e) {
            //Get the CDT on which the QDT is based on via the basedOn dependency
            foreach (EA.Connector con in e.Connectors) {
                if (con.Stereotype.ToString() == CCTS_Types.basedOn.ToString()) {
                    //Get the supplier of the connector
                    return this.repository.GetElementByID(con.SupplierID);                    
                }
            }
            return null;
        }

        

        /// <sUMM2ary>
        /// Returns the XSD-Type for the passed EA Type
        /// </sUMM2ary>
        /// <returns></returns>
        private String getXSDType(EA.Attribute a, EA.Element e) {
            String determinedElementType = "";
            try {
                determinedElementType = XMLTools.getXSDType(a,e);
            }
            catch (XMLException xe) {
                this.appendWarnMessage(xe.Message, this.getPackageName());
                determinedElementType = "string";
            }
            return determinedElementType;
        }

        /// <sUMM2ary>
        /// Adds the necessary Namespaces to the Schema
        /// </sUMM2ary>
        /// <param name="schema"></param>
        private void addNameSpaces(XmlSchema schema) {

            string schemaNamespace = "";

            schema.Namespaces.Add("xsd", "http://www.w3.org/2001/XMLSchema");
            schema.Namespaces.Add("ccts", "urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2");

            //Catch if the baseURN tagged value is empty
            schemaNamespace = XMLTools.getNameSpace(this.repository, this.repository.GetPackageByID(Int32.Parse(this.scope)));
            if (schemaNamespace == "")
                throw new Exception("Please fill the 'baseURN' tagged value of the package. 'baseURN' can not be empty.");

            schema.Namespaces.Add(XMLTools.getNameSpacePrefix(this.repository.GetPackageByID(Int32.Parse(this.scope)), this.TargetNameSpacePrefix), schemaNamespace);
            schema.TargetNamespace = schemaNamespace;
        }


        private void getCheckedOption()
        {
            if (this.annotateElementBox.Checked)
                this.annotate = true;
            else
                this.annotate = false;

            if (this.chkIncludeLinkedSchema.Checked)
                this.blnIncludeLinkedSchema = true;
            else
                this.blnIncludeLinkedSchema = false;

            if (this.chkUseAlias.Checked)
                this.blnAlias = true;
            else
                this.blnAlias = false;
        }

        /// <sUMM2ary>
        /// Generate a schema from the QDT library
        /// </sUMM2ary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnGenerateSchema_Click(object sender, EventArgs e)
        {
            this.resetGenerator(this.scope);

            getCheckedOption();

            ////Annotate or not?
            //if (this.annotateElementBox.Checked)
            //    this.annotate = true;
            //else
            //    this.annotate = false;

            //if (this.chkIncludeLinkedSchema.Checked)
            //    CC_Utils.blnLinkedSchema = true;
            //else
            //    CC_Utils.blnLinkedSchema = false;

            ////Use alias for saved folder or not
            //if (this.chkUseAlias.Checked)
            //    CC_Utils.blnUseAlias = true;
            //else
            //    CC_Utils.blnUseAlias = false;


            if (DEBUG) {
                path = "C:\\Dokumente und Einstellungen\\pliegl\\Desktop\\xsd-schema";
            }
            else {
                DialogResult dr = this.folderBrowserDialog1.ShowDialog(this);

                if (dr.Equals(DialogResult.Cancel)) {
                    folderBrowserDialog1.Dispose();
                    return;
                } 

                path = this.folderBrowserDialog1.SelectedPath;
            }

            if (this.path == null || this.path.Equals("")) {
                this.appendErrorMessage("Please select a location for the generated schemas first.",this.getPackageName());
            }
            else {

                this.path = this.path + "\\";
                //Get the active Package
                EA.Package p = this.repository.GetPackageByID(Int32.Parse(this.scope));

                this.performProgressStep();

                String error = "";
                System.Collections.ICollection result = null;

                this.appendInfoMessage("Starting QDT schema creation. Please wait.", this.getPackageName());

                try {
                    result = generateSchema(p);
                }
                catch (Exception exc) {
                    error = exc.Message;
                }

                //Kein Fehler aufgetreten - schreibe das Ergebnis
                if (error == "") {
                    foreach (XmlSchema schema in result) {
                        
                        String schemaPath = XMLTools.getSavePathForSchema(this.repository.GetPackageByID(Int32.Parse(this.scope)), repository, this.blnAlias);
                        String filename = path + schemaPath + XMLTools.getSchemaName(this.repository.GetPackageByID(Int32.Parse(this.scope)));
                        //Create the path
                        System.IO.Directory.CreateDirectory(path + schemaPath);
                        Stream outputStream = System.IO.File.Open(filename, FileMode.Create);
                        schema.Write(outputStream);
                        outputStream.Close();
                    }
                    this.appendInfoMessage("The schema was created successfully.", this.getPackageName());
                }
                else {
                    this.appendErrorMessage(error, this.getPackageName());
                }

                this.progressBar1.Value = this.progressBar1.Maximum;
            }
        }

        /// <sUMM2ary>
        /// Determine wheter the attribute has use=optional or use=required
        /// </sUMM2ary>
        /// <param name="attribute"></param>
        /// <param name="schemaAttribute"></param>
        private void getOptionalOrRequired(EA.Attribute attribute, XmlSchemaAttribute schemaAttribute) {

            //Get the lower bound of the attribute
            String lowerBound = attribute.LowerBound;
            schemaAttribute.Use = XmlSchemaUse.Required;
            try {
                int i = Int32.Parse(lowerBound);
                if (i == 0)
                    schemaAttribute.Use = XmlSchemaUse.Optional;
            }
            catch (Exception e) { }

        }


        private static void ValidationCallbackOne(object sender, ValidationEventArgs args) {
            throw new XmlSchemaException(args.Message + args.Exception.StackTrace);
        }

        /// <sUMM2ary>
        /// Setze den Text der ausgewählten QDTLibrary
        /// </sUMM2ary>
        private void setActivePackageLabel() {
            EA.Package p = this.repository.GetPackageByID(Int32.Parse(this.scope));
            this.selectedQDTLibrary.Text = p.Element.Name + "<<" + p.Element.Stereotype.ToString() + ">>";
        }

        /// <sUMM2ary>
        /// Performs a step with the progress bar
        /// </sUMM2ary>
        public void performProgressStep() {
            if (this.withGUI) {
                this.progressBar1.PerformStep();
            }
            else {
                //Is there a caller for this class?
                if (caller != null)
                    caller.performProgressStep();
            }
        }

        /// <sUMM2ary>
        /// Append an error message to the status box
        /// </sUMM2ary>
        /// <param name="msg"></param>
        private void appendErrorMessage(String msg, String packageName) {
            if (caller != null) {
                caller.appendMessage("error", msg, this.getPackageName());
            }
            else {
                if (this.withGUI) {
                    this.statusTextBox.Text += "ERROR: (Package: " + packageName + ") " + msg + "\n\n";
                }
            }
        }
        /// <sUMM2ary>
        /// Show a info message in the status box
        /// </sUMM2ary>
        /// <param name="msg"></param>
        private void appendInfoMessage(String msg, String packageName) {
            if (caller != null) {
                caller.appendMessage("info", msg, this.getPackageName());
            }
            else {
                if (this.withGUI) {
                    this.statusTextBox.Text += "INFO: (Package: " + packageName + ") " + msg + "\n\n";
                }
            }
        }
        /// <sUMM2ary>
        /// Show a warn message in the status box
        /// </sUMM2ary>
        /// <param name="msg"></param>
        private void appendWarnMessage(String msg, String packageName) {
            if (caller != null) {
                caller.appendMessage("warn", msg, this.getPackageName());
            }
            else {
                if (this.withGUI)
                    this.statusTextBox.Text += "WARN: (Package: " + packageName + ") " + msg + "\n\n";
            }
        }


        /// <sUMM2ary>
        /// Reset the Text of the StatusTextBox
        /// </sUMM2ary>
        private void resetMessageText() {
            if (this.withGUI)
                this.statusTextBox.Text = "";
        }


        /// <sUMM2ary>
        /// Add the necessary Imports
        /// </sUMM2ary>
        /// <param name="schema"></param>
        private void addImports(XmlSchema schema) {
            //Nothing to do so far
        }

        /// <sUMM2ary>
        /// Return the Annotation for a given cdt
        /// </sUMM2ary>
        /// <param name="name"></param>
        /// <returns></returns>
        private XmlSchemaAnnotation getQDTAnnotation(EA.Element qdt) {
            XmlSchemaAnnotation ann = new XmlSchemaAnnotation();
            XmlSchemaDocumentation doc = new XmlSchemaDocumentation();
            doc.Language = "en";
            XmlDocument xml = new XmlDocument();

            String name = qdt.Name;

            //These arrays hold the names and the values of the annotation
            String[] nodes = { "*UniqueID", 
                "*Acronym", 
                "*DictionaryEntryName", 
                "*Version", 
                "*Definition", 
                "*PrimaryRepresentationTerm", 
                "*DataTypeQualifierTerm", 
                "*PrimitiveType", 
                "*BusinessProcessContextValue", 
                "*GeopoliticalOrRegionContextValue", 
                "*OfficialConstraintContextValue", 
                "*ProductContextValue", 
                "*IndustryContextValue", 
                "*BusinessProcessRoleContextValue", 
                "*SupportingRoleContextValue", 
                "*SystemCapabilitiesContextValue", 
                "*UsageRule", 
                "*BusinessTerm", 
                "*Example" };

            String[] values = { XMLTools.getElementTVValue(CCTS_TV.UniqueID, qdt), 
                "QDT", 
                XMLTools.getElementTVValue(CCTS_TV.DictionaryEntryName, qdt), 
                XMLTools.getElementTVValue(CCTS_TV.Version, qdt), 
                XMLTools.getElementTVValue(CCTS_TV.Definition, qdt), 
                XMLTools.getElementTVValue(CCTS_TV.PrimaryRepresentationTerm, qdt),
                XMLTools.getElementTVValue(CCTS_TV.DataTypeQualifierTerm, qdt),
                XMLTools.getElementTVValue(CCTS_TV.PrimitiveType, qdt),
                XMLTools.getElementTVValue(CCTS_TV.BusinessProcessContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.GeopoliticalOrRegionContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.OfficialConstraintContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.ProductContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.IndustryContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.BusinessProcessRoleContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.SupportingRoleContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.SystemCapabilitiesContextValue, qdt),
                XMLTools.getElementTVValue(CCTS_TV.UsageRule, qdt),
                XMLTools.getElementTVValue(CCTS_TV.BusinessTerm, qdt),
                XMLTools.getElementTVValue(CCTS_TV.Example, qdt)
                };

            XmlNode[] annNodes = new XmlNode[nodes.Length];
            for (int i = 0; i < nodes.Length; i++) {
                //If a node is optional (a node is optional if its name starts with a *)
                //we only include it, if a value is specified
                bool include = true;
                if (nodes[i].Substring(0, 1) == "*" && values[i] == "") {
                    include = false;
                }
                if (include) {
                    XmlNode node = xml.CreateElement("ccts", nodes[i].Replace("*", ""), "urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2");
                    if (values[i] != "")
                        node.InnerText = values[i];
                    annNodes[i] = node;
                }
            }

            doc.Markup = annNodes;
            ann.Items.Add(doc);

            return ann;
        }


        /// <sUMM2ary>
        /// Returns the annoation for an attribute
        /// </sUMM2ary>
        /// <param name="attribute"></param>
        /// <returns></returns>
        private XmlSchemaAnnotation getAttributeAnnotation(EA.Attribute attribute) {
            XmlSchemaAnnotation ann = new XmlSchemaAnnotation();
            XmlSchemaDocumentation doc = new XmlSchemaDocumentation();

            XmlDocument xml = new XmlDocument();

            String name = attribute.Name;
            String card = attribute.LowerBound + ".." + attribute.UpperBound;

            //These arrays hold the names and the values of the annotation
            String[] nodes = { 
                "*Acronym",                  
                "*Name",
                "*Definition", 
                "*Cardinality", 
                "*ObjectClassTerm", 
                "*PropertyTerm", 
                "*PrimitiveType", 
                "*Example" };

            String[] values = {                  
                "SC", 
                XMLTools.getAttributeTVValue(CCTS_TV.Name, attribute), 
                XMLTools.getAttributeTVValue(CCTS_TV.Definition, attribute), 
                card, 
                XMLTools.getAttributeTVValue(CCTS_TV.ObjectClassTerm, attribute),  
                XMLTools.getAttributeTVValue(CCTS_TV.PropertyTerm, attribute),
                XMLTools.getAttributeTVValue(CCTS_TV.PrimitiveType, attribute),
                XMLTools.getAttributeTVValue(CCTS_TV.Example, attribute)
                };

            XmlNode[] annNodes = new XmlNode[nodes.Length];
            for (int i = 0; i < nodes.Length; i++) {
                //If a node is optional (a node is optional if its name starts with a *)
                //we only include it, if a value is specified
                bool include = true;
                if (nodes[i].Substring(0, 1) == "*" && values[i] == "") {
                    include = false;
                }
                if (include) {
                    XmlNode node = xml.CreateElement("ccts", nodes[i].Replace("*", ""), "urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2");
                    if (values[i] != "")
                        node.InnerText = values[i];
                    annNodes[i] = node;
                }
            }

            doc.Markup = annNodes;
            ann.Items.Add(doc);
            return ann;
        }


        /// <sUMM2ary>
        /// Returns the type of the CON element of the passed EA.Element
        /// </sUMM2ary>
        /// <param name="e"></param>
        /// <returns></returns>
        private String getCONAttributeTypeFromElement(EA.Element e) {

            foreach (EA.Attribute attribute in e.Attributes) {
                if (attribute.Stereotype.ToString().Equals(CCTS_Types.CON.ToString()))
                    return attribute.Type;
            }
            return "";
        }


        /// <sUMM2ary>
        /// Add a new import to the schema
        /// </sUMM2ary>
        /// <param name="schema"></param>
        private void addImport(XmlSchema schema, String schemaLocation, String namespace_) {
            XmlSchemaImport xsi1 = new XmlSchemaImport();
            xsi1.SchemaLocation = schemaLocation;
            xsi1.Namespace = namespace_;
            schema.Includes.Add(xsi1);
        }


        /// <sUMM2ary>
        /// Returns an empty String if the schema is not included
        /// If the schema is included, the namespace is returned
        /// </sUMM2ary>
        /// <param name="packageName"></param>
        /// <returns></returns>
        private String isSchemaAlreadyIncluded(String packageName) {
            foreach (AuxilliarySchema aux in this.alreadyCreatedSchemas) {
                if (aux.PackageOfOrigin == packageName)
                    return aux.Namespace;
            }
            return "";
        }


        /// <sUMM2ary>
        /// Cancel Button
        /// </sUMM2ary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnCancel_Click(object sender, EventArgs e) {
            this.Visible = false;
        }

        /// <sUMM2ary>
        /// Returns the name of the current package
        /// </sUMM2ary>
        /// <returns></returns>
        private String getPackageName() {
            return this.repository.GetPackageByID(Int32.Parse(this.scope)).Name.ToString();
        }



        /// <sUMM2ary>
        /// This methods determins, what should be passed to an auxilliary schema generator
        /// If this class itself has already been called by another class, the calling class is passed
        /// otherwise an instance of this class is passed
        /// </sUMM2ary>
        /// <returns></returns>
        private GeneratorCallBackInterface getCaller() {
            if (this.caller == null)
                return this;
            else
                return caller;
        }


        private string isAlreadyInBLGenArray(string packageName)
        {
            foreach (AuxilliarySchema aux in this.alreadyCreatedSchemasBLGen)
            {
                if (aux.PackageOfOrigin == packageName)
                    return aux.Namespace;
            }
            return "";
        }

        #endregion






    }
}