<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:enum767="abs.gov.au:codes:1220" xmlns:enum765="abs.gov.au:codes:1292" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:enum764="urn:iso-org:codes:3166-1:1997" xmlns:enum763="urn:standards.org.au:codes:draft:as4590:2006" xmlns:enum766="urn:standards.org.au:codes:final:as4819:2003" xmlns:enum769="urn:xeda-org:draft:codes:enumerations:2.0.0" xmlns:bie91="urn:xeda-org:draft:data:commonAggregates:2.0.0" xmlns:bie89="urn:xeda-org:draft:data:landAndBuildingAggregates:2.0.0" xmlns:bie24="urn:xeda-org:draft:docs:CommonMessageAssemblies:2.0.0" xmlns:bie25="urn:xeda-org:draft:docs:eDABusinessDomainModel:2.0.0" xmlns:qdt317="urn:xeda-org:draft:types:dataTypes:2.0.0" xmlns:enum778="urn:xml-gov-au:draft:codes:messaging" xmlns:n="urn:xml-gov-au:draft:data:sbdheader:2.0.0" xmlns:n2="urn:xml-gov-au:draft:tm:TransactionModule:0.1" xmlns:qdt333="urn:xml-gov-au:draft:types:MessagingTypes:1.1" xmlns:qdt324="urn:xml-gov-au:draft:types:NameAddressTypes:0.7" xmlns:udt6="urn:xml-gov-au:final:types:coredatatypes:1.0" exclude-result-prefixes="bie24 bie25 bie89 bie91 enum763 enum764 enum765 enum766 enum767 enum769 qdt317 qdt324 xs xsi xsl" xmlns="urn:xml-gov-au:draft:tm:TransactionModule:0.1">
	<xsl:namespace-alias stylesheet-prefix="n2" result-prefix="#default"/>
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/*">
		<n2:TransactionProtocolSuccess>
			<xsl:attribute name="xsi:schemaLocation">
				<xsl:value-of select="'urn:xml-gov-au:draft:tm:TransactionModule:0.1 ../TransactionProtocolSuccess.xsd'"/>
			</xsl:attribute>
			<n2:StandardBusinessMessageHeader>
				<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
					<xsl:for-each select="n:HeaderVersion">
						<n:HeaderVersion>
							<xsl:for-each select="@LanguageIdentifier">
								<xsl:attribute name="LanguageIdentifier">
									<xsl:value-of select="."/>
								</xsl:attribute>
							</xsl:for-each>
							<xsl:for-each select="@LanguageLocaleIdentifier">
								<xsl:attribute name="LanguageLocaleIdentifier">
									<xsl:value-of select="."/>
								</xsl:attribute>
							</xsl:for-each>
							<xsl:value-of select="."/>
						</n:HeaderVersion>
					</xsl:for-each>
				</xsl:for-each>
				<n:SenderPartner>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:ReceiverPartner">
							<xsl:for-each select="n:ID">
								<n:ID>
									<xsl:for-each select="@IdentificationSchemeIdentifier">
										<xsl:attribute name="IdentificationSchemeIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeName">
										<xsl:attribute name="IdentificationSchemeName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeAgencyIdentifier">
										<xsl:attribute name="IdentificationSchemeAgencyIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeAgencyName">
										<xsl:attribute name="IdentificationSchemeAgencyName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeVersionIdentifier">
										<xsl:attribute name="IdentificationSchemeVersionIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeDataURI">
										<xsl:attribute name="IdentificationSchemeDataURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeURI">
										<xsl:attribute name="IdentificationSchemeURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:ID>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:ReceiverPartner">
							<xsl:for-each select="n:Name">
								<n:Name>
									<xsl:for-each select="@LanguageIdentifier">
										<xsl:attribute name="LanguageIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@LanguageLocaleIdentifier">
										<xsl:attribute name="LanguageLocaleIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:Name>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:ReceiverPartner">
							<xsl:for-each select="n:ProcessRole">
								<n:ProcessRole>
									<xsl:for-each select="@CodeListName">
										<xsl:attribute name="CodeListName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeListSchemeURI">
										<xsl:attribute name="CodeListSchemeURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeName">
										<xsl:attribute name="CodeName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:ProcessRole>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:ReceiverPartner">
							<xsl:for-each select="n:Contact">
								<n:Contact>
									<xsl:for-each select="n:Name">
										<n:Name>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:Name>
									</xsl:for-each>
									<xsl:for-each select="n:EmailAddress">
										<n:EmailAddress>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:EmailAddress>
									</xsl:for-each>
									<xsl:for-each select="n:FaxNumber">
										<n:FaxNumber>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:FaxNumber>
									</xsl:for-each>
									<xsl:for-each select="n:TelephoneNumber">
										<n:TelephoneNumber>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:TelephoneNumber>
									</xsl:for-each>
								</n:Contact>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</n:SenderPartner>
				<n:ReceiverPartner>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:SenderPartner">
							<xsl:for-each select="n:ID">
								<n:ID>
									<xsl:for-each select="@IdentificationSchemeIdentifier">
										<xsl:attribute name="IdentificationSchemeIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeName">
										<xsl:attribute name="IdentificationSchemeName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeAgencyIdentifier">
										<xsl:attribute name="IdentificationSchemeAgencyIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeAgencyName">
										<xsl:attribute name="IdentificationSchemeAgencyName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeVersionIdentifier">
										<xsl:attribute name="IdentificationSchemeVersionIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeDataURI">
										<xsl:attribute name="IdentificationSchemeDataURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@IdentificationSchemeURI">
										<xsl:attribute name="IdentificationSchemeURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:ID>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:SenderPartner">
							<xsl:for-each select="n:Name">
								<n:Name>
									<xsl:for-each select="@LanguageIdentifier">
										<xsl:attribute name="LanguageIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@LanguageLocaleIdentifier">
										<xsl:attribute name="LanguageLocaleIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:Name>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:SenderPartner">
							<xsl:for-each select="n:ProcessRole">
								<n:ProcessRole>
									<xsl:for-each select="@CodeListName">
										<xsl:attribute name="CodeListName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeListSchemeURI">
										<xsl:attribute name="CodeListSchemeURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeName">
										<xsl:attribute name="CodeName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:ProcessRole>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:SenderPartner">
							<xsl:for-each select="n:Contact">
								<n:Contact>
									<xsl:for-each select="n:Name">
										<n:Name>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:Name>
									</xsl:for-each>
									<xsl:for-each select="n:EmailAddress">
										<n:EmailAddress>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:EmailAddress>
									</xsl:for-each>
									<xsl:for-each select="n:FaxNumber">
										<n:FaxNumber>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:FaxNumber>
									</xsl:for-each>
									<xsl:for-each select="n:TelephoneNumber">
										<n:TelephoneNumber>
											<xsl:for-each select="@LanguageIdentifier">
												<xsl:attribute name="LanguageIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@LanguageLocaleIdentifier">
												<xsl:attribute name="LanguageLocaleIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:TelephoneNumber>
									</xsl:for-each>
								</n:Contact>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</n:ReceiverPartner>
				<n:DocumentIdentification>
					<n:Identifier>
						<xsl:value-of select="''"/>
					</n:Identifier>
					<n:CreationDateAndTime>
						<xsl:value-of select="''"/>
					</n:CreationDateAndTime>
					<n:Name>
						<xsl:value-of select="''"/>
					</n:Name>
					<n:Version>
						<xsl:value-of select="''"/>
					</n:Version>
				</n:DocumentIdentification>
				<n:BusinessScope>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:BusinessScope">
							<xsl:for-each select="n:Type">
								<n:Type>
									<xsl:for-each select="@CodeListName">
										<xsl:attribute name="CodeListName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeListSchemeURI">
										<xsl:attribute name="CodeListSchemeURI">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@CodeName">
										<xsl:attribute name="CodeName">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:Type>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:BusinessScope">
							<xsl:for-each select="n:Name">
								<n:Name>
									<xsl:for-each select="@LanguageIdentifier">
										<xsl:attribute name="LanguageIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@LanguageLocaleIdentifier">
										<xsl:attribute name="LanguageLocaleIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:Name>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
						<xsl:for-each select="n:BusinessScope">
							<xsl:for-each select="n:InstanceIdentifier">
								<n:InstanceIdentifier>
									<xsl:for-each select="@LanguageIdentifier">
										<xsl:attribute name="LanguageIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:for-each select="@LanguageLocaleIdentifier">
										<xsl:attribute name="LanguageLocaleIdentifier">
											<xsl:value-of select="."/>
										</xsl:attribute>
									</xsl:for-each>
									<xsl:value-of select="."/>
								</n:InstanceIdentifier>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
					<n:AdditionalCorrelationInformation>
						<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
							<xsl:for-each select="n:BusinessScope">
								<xsl:for-each select="n:AdditionalCorrelationInformation">
									<xsl:for-each select="n:RequestingDocumentIdentifier">
										<n:RequestingDocumentIdentifier>
											<xsl:for-each select="@IdentificationSchemeIdentifier">
												<xsl:attribute name="IdentificationSchemeIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeName">
												<xsl:attribute name="IdentificationSchemeName">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeAgencyIdentifier">
												<xsl:attribute name="IdentificationSchemeAgencyIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeAgencyName">
												<xsl:attribute name="IdentificationSchemeAgencyName">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeVersionIdentifier">
												<xsl:attribute name="IdentificationSchemeVersionIdentifier">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeDataURI">
												<xsl:attribute name="IdentificationSchemeDataURI">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:for-each select="@IdentificationSchemeURI">
												<xsl:attribute name="IdentificationSchemeURI">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:RequestingDocumentIdentifier>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
						<xsl:for-each select="*[local-name()='StandardBusinessMessageHeader']">
							<xsl:for-each select="n:BusinessScope">
								<xsl:for-each select="n:AdditionalCorrelationInformation">
									<xsl:for-each select="n:RequestingDocumentCreationDateTime">
										<n:RequestingDocumentCreationDateTime>
											<xsl:for-each select="@Format">
												<xsl:attribute name="Format">
													<xsl:value-of select="."/>
												</xsl:attribute>
											</xsl:for-each>
											<xsl:value-of select="."/>
										</n:RequestingDocumentCreationDateTime>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</n:AdditionalCorrelationInformation>
				</n:BusinessScope>
			</n2:StandardBusinessMessageHeader>
			<n2:ProtocolSuccess_Status>
				<n2:Success_Description>
					<xsl:value-of select="''"/>
				</n2:Success_Description>
			</n2:ProtocolSuccess_Status>
		</n2:TransactionProtocolSuccess>
	</xsl:template>
</xsl:stylesheet>
